version: "3.8"

services:
  cstore_nginx:
    build:
      context: ../
      dockerfile: ./docker/services/nginx/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/sites-available:/etc/nginx/sites-available
      - ./services/nginx/logs/users_api:/var/log/nginx/users_api
      - ./services/nginx/logs/cart_api:/var/log/nginx/cart_api
      - ./services/nginx/logs/store_api:/var/log/nginx/store_api
    depends_on:
      - cstore_users_api
      - cstore_store_api
      - cstore_cart_api
    networks:
      - cstore

  cstore_users_api:
    build:
      context: ../
      dockerfile: ./docker/services/users_api/Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - ../services/users_api:/users_api
      - ${GOPATH:-../gopath}:/go
    env_file:
      - ./services/common.env
      - ./services/users_api/.env
    depends_on:
      - cstore_mysql
    networks:
      - cstore

  cstore_store_api:
    build:
      context: ../
      dockerfile: ./docker/services/store_api/Dockerfile
    restart: on-failure
    ports:
      - "8083:8083"
    volumes:
      - ../services/store_api:/store_api
      - ${GOPATH:-../gopath}:/go
    env_file:
      - ./services/common.env
      - ./services/store_api/.env
    networks:
      - cstore

  cstore_cart_api:
    build:
      context: ../
      dockerfile: ./docker/services/cart_api/Dockerfile
    restart: on-failure
    ports:
      - "8084:8084"
    volumes:
      - ../services/cart_api:/cart_api
      - ${GOPATH:-../gopath}:/go
    env_file:
      - ./services/common.env
      - ./services/cart_api/.env
    networks:
      - cstore

  #cstore_android_app:
  #  build:
  #    context: ../
  #    dockerfile: ./docker/services/android_app/Dockerfile
  #  restart: unless-stopped
  #  volumes:
  #    - ../services/android_app:/android_app
  #  env_file:
  #    - ./services/common.env
  #    - ./services/android_app/.env
  #  networks:
  #    - cstore

  cstore_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: on-failure
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=cstore_mysql
    depends_on:
      - cstore_mysql
    networks:
      - cstore

  cstore_mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: on-failure
    env_file:
      - ./services/mysql/.env
    volumes:
      - ./services/mysql/data:/mysql/mysql-data
    networks:
      - cstore

  cstore_mysql_init:
    build:
      context: ../
      dockerfile: ./docker/services/mysql/init/Dockerfile
    restart: on-failure
    depends_on:
      - cstore_mysql
    networks:
      - cstore

networks:
  cstore:
    driver: bridge
